### ISSUE TITLE
Migration of peripheral files: objects versus arrays

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#122]
Right now all of the peripheral files are setup in having both arrays and objects.

```yaml
registers:
    - registerName:
        address: 0x60
```

This is unnecessary, as YAML files can contain an array or contain objects. The proper way to do this is by using object keys directly.

```yaml
registers:
    registerName:
        address: 0x60
```

Cleaning this up will be a large refactor but will improve the codebase quite a bit and serve as more idiomatic YAML.
