### ISSUE TITLE
Support SPI

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#209]
Implement a basic SPI mode that can use a mix of registers or [serialized message buffers](http://github.com/google/emboss). If it uses registers and supports multiple transport layers, how do we separate I2C and SPI?

This format is already supported in several platforms including [Arduino](https://www.arduino.cc/en/reference/SPI) and [Android Things](https://developer.android.com/things/sdk/pio/spi) and uses [transactions](https://www.arduino.cc/en/Tutorial/SPITransaction).

We should update the JSON schema at the same time to perform proper validation.

Example spec:

```yaml
spi:
  # These two params combined make up AThings SPI modes 0-3 in a quadrant
  clockPolarity: LOW | HIGH
  clockPhase: LEADING | TRAILING # clock edge
  frequency: 16000 # 16KHz
  endianness: # Same as in I2C (make this a separate type we reference?)
  word: 8 # bits
  format: REGISTER | SERIALIZATION # Depends on whether we use registers or we use serialized message buffers
```
