### ISSUE TITLE
Cyanochew editor

### ISSUE THREAD

**Issue by polfeliu** [google/cyanobyte#267]
Hello Everyone,

A few months ago I created a code generation project named cantata (https://github.com/polfeliu/cantata), that generates code for ECUs connected to CAN networks according to the spec a .dbc file. Something similar to cyanobye .yaml files. This is very standard in automotive. The big difference is that these files typically edited with a GUI, the most known being Vector's CANdb++ editor.

So, allow me to introduce you to Cyanochew! A cyanobyte GUI editor, to create and edit .yaml files according to the spec as fast as possible, chewing through datasheets. Also, byte -> bite -> chew, all puns intended :)
I think having a GUI is important to grow the library of supported devices and make cyanobyte something more widely used. 

https://github.com/polfeliu/Cyanochew

Right now the project is a minimum viable product and many features are still to be implemented, for example input validation for some types of data.
Feel free to open new issues proposing changes or new features, and to exchange ideas. For example, I don't have a solid plan on how functions and extensions should be edited, and for now they are ignored (they won't be removed from files but there is no way to edit them)

One cool thing about Info, I2C and SPI is that the UI is dynamically generated from to the json spec. So it will be very easy to add newer options of the cyanobyte. The register editor (Tab Registers, Select register, Edit) was a big challenge but now it's working really well.

**Comment by polfeliu** [comment]
@Fleker

**Comment by Fleker** [comment]
This is a really great tool. Thanks for sharing it! Setting up functions are definitely a more convoluted part of the spec in general, and extensions are even more broad and open to interpretation. Having the basic parts to setup the file and create that boilerplate should go a long way.

I can see there's  good similarity b/w CAN and I2C in some ways, although CAN may be specced more formally than I2C, it's good that there's interest in the ideas more generally.

**Comment by polfeliu** [comment]
Thank you! yes, CAN lower layers are definitely more standardized, but the candb standard doesn't cover some weird implementations that some manufacturers occasionally do. 

I had some ideas of doing some kind of pseudocode for functions, or an editor based on blocks, simulink like. 
There are some interesting helpers out there: https://github.com/leon-thomm/Ryven, https://github.com/gangtao/pyflow

One thing that will be a must is the ability to test or plot functions with dummy data.

**Comment by Fleker** [comment]
Handling edge cases is very tricky, which is an area where defining functions can help massage the data for both CAN and I2C.

A visual editor for functions could be very interesting if there was an easy way to parse that and reformat it.

But ensuring it works through tests is very valuable too. I've thought about having a way to let one define example values from a register to use for simulations. Then you could generate a virtual driver in a console and interact with it through pure logic rather than needing a physical device.

**Comment by polfeliu** [comment]
I don't know how it would work but being able to define some behaviour of IC's is really interesting. 
Being able to emulate, also in hw, would be very useful for validation purposes. Its not the case for hobbyist but for professional mcu validation being able to emulate and then introduce malfunctions of the IC is somewhat typical for functional safety applications. 
Also useful for sensors that capture difficult or expensive to reproduce environments (Light intensity, high voltage, current, moisture, smoke... the list is long)

The functions editor would need to be limited to the functions the specs supports. Then it should be straight forward to parse and deparse.

**Comment by Fleker** [comment]
I think a simple approach is to define one or multiple example values from an expected sensor (maybe with additional semantic information)

```yaml
registerA:
    example: 0x43
    # Or several possible values
    example: [0x43, 0x36]
    # Or maybe semantics
    example:
        valid: [0x43, 0x36]
        error: 0x00
        # Custom error keys?
       err_disconnected: 0x77
```

Then a new template can be developed that substitutes the existing I2C calls with simple returns so that this can be processed in a hardware-free environment (QA, development, CI, etc.)

```python
def read_register_a():
    # return i2c.read(REGISTER_A_ADDR)
    return 0x43 # Obtained from example field
```

Then in cases like the BMP180, we can still evaluate the functionality of higher-level operations like temperature calculation because all it depends on are register values. If those are mocked, then everything else can be continue to be checked and validated.

**Comment by polfeliu** [comment]
If I understand correctly, the value of the registers would be calculated when reading or writing from SPI or I2C. In software its no problem but in hardware this has the drawback of requiring a fast calculation to respond, limiting what can be done. I think the emulation should have a state, meaning the emulator should have a region of memory with the registers that it can read and write and the magic should happen behind doors. In Vector CANoe there is something called "environment variables" that describe real values of the state of a simulated car (we should find another name). Then with CAPL/Simulink/... it emulates the behaviour of the ECU. 

These env vars could be controlled via a generic interface. (In a SW environment with function calls, in hw with ethernet, usb...)
![draw io_Wk461voR2j](https://user-images.githubusercontent.com/3652353/113385538-a0f24780-9388-11eb-9fda-6dc31c9b7e87.png)

Then, to actually emulate the behaviour there would be a "worker" (a better name can be found too) that does calculations and sets sig vars and registers/fields doing calculations whenever a event triggers.


```yaml
emulation:
    envvars:
        temperature: float64
        humidity: float32
    workers:
        workerTemperature:
            triggers:
                - change: "#/emulation/envvars/temperature"
                - every: 200 ms
            function: #Same or similar to regular functions
                variables:
                - somevariable
                logic:
                - somevariable
                    - division
                        -"#/emulation/envvars/temperature"
                        - 128
                 - setRegister
                      register: "#/register/temp"
                      value: "somevariable"                     
````
Is there a command in functions to modify the contents of a register/field? If not it would be needed in this case and could also be used in regular functions

Anyway, I think this could answer both simple and complex emulations in software and in hardware
