### ISSUE TITLE
Add changelog generation

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#51]
Once we start tagging releases, we can add this to the cloud build sequence to get changelogs:

```yaml
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', './git-presubmit-linter/tools/changelog.sh > changelog.txt']
  id: 'Generate changelog'
  waitFor: ['Download Git Presubmit Linter']
```
