### ISSUE TITLE
Make spec->license->name spdx compliant

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#6]
Using a standardized set of labels will promote the use of codegen and other automated tooling. SPDX has a formal list of licenses and identifiers.
https://spdx.org/licenses/

In the spec, we'd modify:

```yaml
license:
        name: 'Apache-2.0'
        url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
```

But since this is a standard, we could omit the `url` field as it'd only link to one place by default.

```yaml
license:
        name: 'Apache-2.0'
```
