### ISSUE TITLE
Enable a hardware chip to go to two different addresses

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#60]
Some I2C devices can have more than one possible hardware address, often with a jumper or pin you drive HIGH/LOW.

To handle these, we could have a constant address or a list. If it's a list, transform the constructor to have the address. This address is then validated before continuing.

```yaml
i2c:
    address:
        - 0x18
        - 0x19 # If GPIO1 is logic HIGH
```

```python
mcp9808 = Mcp9808(0x18)
```

Should this be an enum that is exported?

```python
mcp9808 = Mcp9808(Mcp9808.I2C_ADDRESS_0x18)
```
