### ISSUE TITLE
Spec for calling functions with a function

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#61]
How to call a different function, with parameters

```yaml
calcFahrenheit:
  - logic:
    - a : = temp_celsius
      - i: 7
```

Becomes something like:

```
def calcFahrenheit():
  a = temp_celsius(i = 7)
```

Order matters for languages without named arguments.

**Comment by Fleker** [comment]
That's not value YAML. You'd need something more like:

```yaml
- logic:
  - a:
    - temp_celcius:
      - i: 7
```
