### ISSUE TITLE
Spec should include endianness

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#8]
If the communication protocol is i2c, there should be a way to specify endianness. Some devices are little endian, while others are big endian. If there's a mismatch, all of the data will be sent incorrectly.

```yaml
i2c:
    addressType: '7-bit'
    address: 0x18
    addressMask: 0x78
    endian: little endian // or big endian
```
