### ISSUE TITLE
Specification extensions

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#80]
Have some sort of way to provide additional peripheral data in the spec if it doesn't have a specific key.

**Comment by Fleker** [comment]
```yaml
i2c:
    address: 0x10
    'x-i2c-jawn': <any-value>

extensions:
    <any-key-name>: <any-value>
```
